AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Layer with Panda

  Sample SAM Template for SAMLayerTest

Resources:  
  lambdaLayerPandas:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambda-layer-pandas
      ContentUri: ./
      CompatibleRuntimes:        
        - python3.8
        - python3.7
      RetentionPolicy: Retain

